const MoviesApiUrl = 'https://api.nomoreparties.co';

const MOVIES_COUNT_DESKTOP = 12;
const EXPAND_MOVIES_COUNT_DESKTOP = 3;
const MOVIES_COUNT_TABLET = 8;
const EXPAND_MOVIES_COUNT_TABLET = 2;
const MOVIES_COUNT_PHONE = 5;
const EXPAND_MOVIES_COUNT_PHONE = 1;
const SHORT_MOVIE_DURATION = 40;
export {
  MoviesApiUrl,
  MOVIES_COUNT_DESKTOP,
  EXPAND_MOVIES_COUNT_DESKTOP,
  MOVIES_COUNT_TABLET,
  EXPAND_MOVIES_COUNT_TABLET,
  MOVIES_COUNT_PHONE,
  EXPAND_MOVIES_COUNT_PHONE,
  SHORT_MOVIE_DURATION,
};
